#!/usr/bin/env node

const { execSync } = require('child_process');
const path = require('path');

// Get the directory of this script
const scriptDir = __dirname;
const cliPath = path.join(scriptDir, 'src/cli.js');

// Get command line arguments
const args = process.argv.slice(2);

// Build the babel-node command
const command = [
  'babel-node',
  '--presets', '@babel/preset-env,@babel/preset-react',
  cliPath,
  ...args
].join(' ');

try {
  execSync(command, { stdio: 'inherit' });
} catch (error) {
  process.exit(error.status || 1);
}