#!/usr/bin/env node

// Production CLI wrapper - requires built version
const { spawn } = require('child_process');
const path = require('path');

// Get the directory of this script
const scriptDir = __dirname;

// Determine if we're in development or production
const isDev = scriptDir.includes('node_modules') === false;

if (isDev) {
  // Development mode - use babel-node
  console.log('Running in development mode...');
  const babel = spawn('npx', [
    'babel-node',
    '--presets', '@babel/preset-env,@babel/preset-react',
    path.join(scriptDir, 'src/cli.js'),
    ...process.argv.slice(2)
  ], {
    stdio: 'inherit',
    shell: true
  });
  
  babel.on('exit', (code) => {
    process.exit(code);
  });
} else {
  // Production mode - use built version
  require('./dist/src/cli.js');
}